kernel : Python (Pixi)

In [ ]:
import anndata as ad
import gc
import os
import pandas as pd
import scanpy as sc
from scipy.sparse import csr_matrix
from pipeline.utils.env import find_env_dir

raw_data_dir = find_env_dir("RAW_DATA")
pre_h5ad_dir = find_env_dir("PRE_H5AD")

SERIES = "pokatayev"
human_data_dir = os.path.join(raw_data_dir, SERIES, "SCP2927", "anndata")
mouse_data_dir = os.path.join(raw_data_dir, SERIES, "SCP3384", "anndata")

#### Human Dataset

In [ ]:
HUMAN_FIBROBLAST_FILE = "scp_xenium_human_fib.h5ad"
human_fibroblast_adata = sc.read_h5ad(os.path.join(human_data_dir, HUMAN_FIBROBLAST_FILE))
if not isinstance(human_fibroblast_adata.X, csr_matrix):
    human_fibroblast_adata.X = csr_matrix(human_fibroblast_adata.X)

assert isinstance(human_fibroblast_adata.obs, pd.DataFrame)
human_fibroblast_adata.obs["donor"] = human_fibroblast_adata.obs["donor_id"]
human_fibroblast_adata.obs["sample"] = human_fibroblast_adata.obs["biosample_id"]
human_fibroblast_adata.obs["organ"] = human_fibroblast_adata.obs["organ__ontology_label"]
human_fibroblast_adata.obs["genotype"] = human_fibroblast_adata.obs["genotype"]
human_fibroblast_adata.obs["treatment"] = human_fibroblast_adata.obs["treatment"]
human_fibroblast_adata.obs["celltype"] = human_fibroblast_adata.obs["celltype"]
human_fibroblast_adata.obs["x_axis"] = human_fibroblast_adata.obs["x_centroid"]
human_fibroblast_adata.obs["y_axis"] = human_fibroblast_adata.obs["y_centroid"]
human_fibroblast_adata.obs["slide"] = human_fibroblast_adata.obs["slide_id"]
human_fibroblast_adata.obs["broad_celltype"] = "fibroblast"
human_fibroblast_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series", ]
human_fibroblast_adata.obs.drop(columns = [c for c in human_fibroblast_adata.obs.columns if c not in keep], inplace=True) #type: ignore

human_fibroblast_adata.obs.head() #type: ignore

In [ ]:
HUMAN_EPITHELIAL_FILE = "scp_xenium_human_epi.h5ad"
human_epithelial_adata = sc.read_h5ad(os.path.join(human_data_dir, HUMAN_EPITHELIAL_FILE))
if not isinstance(human_epithelial_adata.X, csr_matrix):
    human_epithelial_adata.X = csr_matrix(human_epithelial_adata.X)

assert isinstance(human_epithelial_adata.obs, pd.DataFrame)
human_epithelial_adata.obs["donor"] = human_epithelial_adata.obs["donor_id"]
human_epithelial_adata.obs["sample"] = human_epithelial_adata.obs["biosample_id"]
human_epithelial_adata.obs["organ"] = human_epithelial_adata.obs["organ__ontology_label"]
human_epithelial_adata.obs["genotype"] = human_epithelial_adata.obs["genotype"]
human_epithelial_adata.obs["treatment"] = human_epithelial_adata.obs["treatment"]
human_epithelial_adata.obs["celltype"] = human_epithelial_adata.obs["celltype"]
human_epithelial_adata.obs["x_axis"] = human_epithelial_adata.obs["x_centroid"]
human_epithelial_adata.obs["y_axis"] = human_epithelial_adata.obs["y_centroid"]
human_epithelial_adata.obs["slide"] = human_epithelial_adata.obs["slide_id"]
human_epithelial_adata.obs["broad_celltype"] = "epithelial"
human_epithelial_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
human_epithelial_adata.obs.drop(columns = [c for c in human_epithelial_adata.obs.columns if c not in keep], inplace=True) #type: ignore

human_epithelial_adata.obs.head() #type: ignore

In [ ]:
HUMAN_STROMAL_FILE = "scp_xenium_human_stroma.h5ad"
human_stromal_adata = sc.read_h5ad(os.path.join(human_data_dir, HUMAN_STROMAL_FILE))
if not isinstance(human_stromal_adata.X, csr_matrix):
    human_stromal_adata.X = csr_matrix(human_stromal_adata.X)

assert isinstance(human_stromal_adata.obs, pd.DataFrame)
human_stromal_adata.obs["donor"] = human_stromal_adata.obs["donor_id"]
human_stromal_adata.obs["sample"] = human_stromal_adata.obs["biosample_id"]
human_stromal_adata.obs["organ"] = human_stromal_adata.obs["organ__ontology_label"]
human_stromal_adata.obs["genotype"] = human_stromal_adata.obs["genotype"]
human_stromal_adata.obs["treatment"] = human_stromal_adata.obs["treatment"]
human_stromal_adata.obs["celltype"] = human_stromal_adata.obs["celltype"]
human_stromal_adata.obs["x_axis"] = human_stromal_adata.obs["x_centroid"]
human_stromal_adata.obs["y_axis"] = human_stromal_adata.obs["y_centroid"]
human_stromal_adata.obs["slide"] = human_stromal_adata.obs["slide_id"]
human_stromal_adata.obs["broad_celltype"] = "stromal"
human_stromal_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
human_stromal_adata.obs.drop(columns = [c for c in human_stromal_adata.obs.columns if c not in keep], inplace=True) #type: ignore

human_stromal_adata.obs.head() #type: ignore

In [ ]:
HUMAN_LYMPHOID_FILE = "scp_xenium_human_lymph.h5ad"
human_lymphoid_adata = sc.read_h5ad(os.path.join(human_data_dir, HUMAN_LYMPHOID_FILE))
if not isinstance(human_lymphoid_adata.X, csr_matrix):
    human_lymphoid_adata.X = csr_matrix(human_lymphoid_adata.X)

assert isinstance(human_stromal_adata.obs, pd.DataFrame)
human_lymphoid_adata.obs["donor"] = human_lymphoid_adata.obs["donor_id"]
human_lymphoid_adata.obs["sample"] = human_lymphoid_adata.obs["biosample_id"]
human_lymphoid_adata.obs["organ"] = human_lymphoid_adata.obs["organ__ontology_label"]
human_lymphoid_adata.obs["genotype"] = human_lymphoid_adata.obs["genotype"]
human_lymphoid_adata.obs["treatment"] = human_lymphoid_adata.obs["treatment"]
human_lymphoid_adata.obs["celltype"] = human_lymphoid_adata.obs["celltype"]
human_lymphoid_adata.obs["x_axis"] = human_lymphoid_adata.obs["x_centroid"]
human_lymphoid_adata.obs["y_axis"] = human_lymphoid_adata.obs["y_centroid"]
human_lymphoid_adata.obs["slide"] = human_lymphoid_adata.obs["slide_id"]
human_lymphoid_adata.obs["broad_celltype"] = "lymphoid"
human_lymphoid_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
human_lymphoid_adata.obs.drop(columns = [c for c in human_lymphoid_adata.obs.columns if c not in keep], inplace=True) #type: ignore

human_lymphoid_adata.obs.head() #type: ignore

In [ ]:
HUMAN_MYELOID_FILE = "scp_xenium_human_myeloid.h5ad"
human_myeloid_adata = sc.read_h5ad(os.path.join(human_data_dir, HUMAN_MYELOID_FILE))
if not isinstance(human_myeloid_adata.X, csr_matrix):
    human_myeloid_adata.X = csr_matrix(human_myeloid_adata.X)

assert isinstance(human_myeloid_adata.obs, pd.DataFrame)
human_myeloid_adata.obs["donor"] = human_myeloid_adata.obs["donor_id"]
human_myeloid_adata.obs["sample"] = human_myeloid_adata.obs["biosample_id"]
human_myeloid_adata.obs["organ"] = human_myeloid_adata.obs["organ__ontology_label"]
human_myeloid_adata.obs["genotype"] = human_myeloid_adata.obs["genotype"]
human_myeloid_adata.obs["treatment"] = human_myeloid_adata.obs["treatment"]
human_myeloid_adata.obs["celltype"] = human_myeloid_adata.obs["celltype"]
human_myeloid_adata.obs["x_axis"] = human_myeloid_adata.obs["x_centroid"]
human_myeloid_adata.obs["y_axis"] = human_myeloid_adata.obs["y_centroid"]
human_myeloid_adata.obs["slide"] = human_myeloid_adata.obs["slide_id"]
human_myeloid_adata.obs["broad_celltype"] = "myeloid"
human_myeloid_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
human_myeloid_adata.obs.drop(columns = [c for c in human_myeloid_adata.obs.columns if c not in keep], inplace=True) #type: ignore

human_myeloid_adata.obs.head() #type: ignore

In [ ]:
human_adata_list = [human_fibroblast_adata, human_epithelial_adata, human_stromal_adata, human_lymphoid_adata, human_myeloid_adata, ]
reference_columns = set(human_adata_list[0].obs.columns)

for adata in human_adata_list:
    if set(adata.obs.columns) != reference_columns:
        raise ValueError("obs of adatas do not match!")

human_adata = ad.concat(human_adata_list, join="outer")
del human_adata_list
gc.collect()

In [ ]:
human_adata.obs.index = human_adata.obs.index.astype(str)
human_adata.var.index = human_adata.var.index.astype(str)
human_adata.write_h5ad(os.path.join(pre_h5ad_dir, SERIES + "_human_raw.h5ad"))
del human_adata
gc.collect()

#### Mouse Dataset

In [ ]:
MOUSE_FIBROBLAST_FILE = "scp_xenium_mm_fib.h5ad"
mouse_fibroblast_adata = sc.read_h5ad(os.path.join(mouse_data_dir, MOUSE_FIBROBLAST_FILE))
if not isinstance(mouse_fibroblast_adata.X, csr_matrix):
    mouse_fibroblast_adata.X = csr_matrix(mouse_fibroblast_adata.X)

assert isinstance(mouse_fibroblast_adata.obs, pd.DataFrame)
mouse_fibroblast_adata.obs["donor"] = mouse_fibroblast_adata.obs["donor_id"]
mouse_fibroblast_adata.obs["sample"] = mouse_fibroblast_adata.obs["biosample_id"]
mouse_fibroblast_adata.obs["organ"] = mouse_fibroblast_adata.obs["organ__ontology_label"]
mouse_fibroblast_adata.obs["genotype"] = mouse_fibroblast_adata.obs["genotype"]
mouse_fibroblast_adata.obs["treatment"] = mouse_fibroblast_adata.obs["treatment"]
mouse_fibroblast_adata.obs["celltype"] = mouse_fibroblast_adata.obs["celltype"]
mouse_fibroblast_adata.obs["x_axis"] = mouse_fibroblast_adata.obs["x_centroid"]
mouse_fibroblast_adata.obs["y_axis"] = mouse_fibroblast_adata.obs["y_centroid"]
mouse_fibroblast_adata.obs["slide"] = mouse_fibroblast_adata.obs["slide_id"]
mouse_fibroblast_adata.obs["broad_celltype"] = "fibroblast"
mouse_fibroblast_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series", ]
mouse_fibroblast_adata.obs.drop(columns = [c for c in mouse_fibroblast_adata.obs.columns if c not in keep], inplace=True) #type: ignore

mouse_fibroblast_adata.obs.head() #type: ignore

,organ,genotype,treatment,celltype,donor,sample,x_axis,y_axis,slide,broad_celltype,series
aablldkp-1-0,colon,WT,DSS,mWNT5B+ Nrg1-hi,WT1-DSS,WT1-DSS,318.124481,2625.163330,0022827,fibroblast,pokatayev
aacdoocg-1-0,colon,WT,DSS,mWNT5B+ Nrg1-hi,WT1-DSS,WT1-DSS,641.599365,2753.017578,0022827,fibroblast,pokatayev
aacfhepn-1-0,colon,WT,DSS,mWNT5B+ Nrg1-hi,WT1-DSS,WT1-DSS,464.831268,2593.402588,0022827,fibroblast,pokatayev
aacfnlfd-1-0,colon,WT,DSS,mWNT5B+ Nrg1-hi,WT1-DSS,WT1-DSS,457.515045,2596.182373,0022827,fibroblast,pokatayev
aackhpdg-1-0,colon,WT,DSS,mWNT5B+ Ptgis-hi,WT1-DSS,WT1-DSS,433.132172,2551.246338,0022827,fibroblast,pokatayev

In [ ]:
MOUSE_EPITHELIAL_FILE = "scp_xenium_mm_epi.h5ad"
mouse_epithelial_adata = sc.read_h5ad(os.path.join(mouse_data_dir, MOUSE_EPITHELIAL_FILE))
if not isinstance(mouse_epithelial_adata.X, csr_matrix):
    mouse_epithelial_adata.X = csr_matrix(mouse_epithelial_adata.X)

assert isinstance(mouse_epithelial_adata.obs, pd.DataFrame)
mouse_epithelial_adata.obs["donor"] = mouse_epithelial_adata.obs["donor_id"]
mouse_epithelial_adata.obs["sample"] = mouse_epithelial_adata.obs["biosample_id"]
mouse_epithelial_adata.obs["organ"] = mouse_epithelial_adata.obs["organ__ontology_label"]
mouse_epithelial_adata.obs["genotype"] = mouse_epithelial_adata.obs["genotype"]
mouse_epithelial_adata.obs["treatment"] = mouse_epithelial_adata.obs["treatment"]
mouse_epithelial_adata.obs["celltype"] = mouse_epithelial_adata.obs["celltype"]
mouse_epithelial_adata.obs["x_axis"] = mouse_epithelial_adata.obs["x_centroid"]
mouse_epithelial_adata.obs["y_axis"] = mouse_epithelial_adata.obs["y_centroid"]
mouse_epithelial_adata.obs["slide"] = mouse_epithelial_adata.obs["slide_id"]
mouse_epithelial_adata.obs["broad_celltype"] = "epithelial"
mouse_epithelial_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
mouse_epithelial_adata.obs.drop(columns = [c for c in mouse_epithelial_adata.obs.columns if c not in keep], inplace=True) #type: ignore

mouse_epithelial_adata.obs.head() #type: ignore

,organ,genotype,treatment,celltype,donor,sample,x_axis,y_axis,slide,broad_celltype,series
aaaafepm-1-0,colon,WT,DSS,Proximal colonocytes,WT1-DSS,WT1-DSS,627.923950,1938.716431,0022827,epithelial,pokatayev
aaaajopn-1-0,colon,WT,DSS,Proximal immature colonocytes,WT1-DSS,WT1-DSS,626.592285,1928.387329,0022827,epithelial,pokatayev
aaaalgii-1-0,colon,WT,DSS,Proximal immature colonocytes,WT1-DSS,WT1-DSS,638.152283,1958.203125,0022827,epithelial,pokatayev
aaabeihd-1-0,colon,WT,DSS,Mid immature colonocytes I,WT1-DSS,WT1-DSS,667.175171,1972.483765,0022827,epithelial,pokatayev
aaabjjao-1-0,colon,WT,DSS,Mid immature colonocytes II,WT1-DSS,WT1-DSS,622.093506,1964.790649,0022827,epithelial,pokatayev

In [ ]:
MOUSE_IMMUNE_FILE = "scp_xenium_mm_immune.h5ad"
mouse_immune_adata = sc.read_h5ad(os.path.join(mouse_data_dir, MOUSE_IMMUNE_FILE))
if not isinstance(mouse_immune_adata.X, csr_matrix):
    mouse_immune_adata.X = csr_matrix(mouse_immune_adata.X)

assert isinstance(mouse_immune_adata.obs, pd.DataFrame)
mouse_immune_adata.obs["donor"] = mouse_immune_adata.obs["donor_id"]
mouse_immune_adata.obs["sample"] = mouse_immune_adata.obs["biosample_id"]
mouse_immune_adata.obs["organ"] = mouse_immune_adata.obs["organ__ontology_label"]
mouse_immune_adata.obs["genotype"] = mouse_immune_adata.obs["genotype"]
mouse_immune_adata.obs["treatment"] = mouse_immune_adata.obs["treatment"]
mouse_immune_adata.obs["celltype"] = mouse_immune_adata.obs["celltype"]
mouse_immune_adata.obs["x_axis"] = mouse_immune_adata.obs["x_centroid"]
mouse_immune_adata.obs["y_axis"] = mouse_immune_adata.obs["y_centroid"]
mouse_immune_adata.obs["slide"] = mouse_immune_adata.obs["slide_id"]
mouse_immune_adata.obs["broad_celltype"] = "immune"
mouse_immune_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
mouse_immune_adata.obs.drop(columns = [c for c in mouse_immune_adata.obs.columns if c not in keep], inplace=True) #type: ignore

mouse_immune_adata.obs.head() #type: ignore

,organ,genotype,treatment,celltype,donor,sample,x_axis,y_axis,slide,broad_celltype,series
aaafnebi-1-0,colon,WT,DSS,CD8+ T cells(intraepithelial),WT1-DSS,WT1-DSS,664.775330,2176.648438,0022827,immune,pokatayev
aaakkkeh-1-0,colon,WT,DSS,Conventional dendritic cells type I,WT1-DSS,WT1-DSS,585.083618,2068.828125,0022827,immune,pokatayev
aabackol-1-0,colon,WT,DSS,Cx3cr1-hi macrophages,WT1-DSS,WT1-DSS,392.618805,2577.339355,0022827,immune,pokatayev
aacllpgl-1-0,colon,WT,DSS,CD8+ T cells(intraepithelial),WT1-DSS,WT1-DSS,608.436890,2241.239990,0022827,immune,pokatayev
aaelbihp-1-0,colon,WT,DSS,CD8+ T cells(intraepithelial),WT1-DSS,WT1-DSS,763.272278,2510.568359,0022827,immune,pokatayev

In [ ]:
MOUSE_STROMAL_FILE = "scp_xenium_mm_stroma.h5ad"
mouse_stromal_adata = sc.read_h5ad(os.path.join(mouse_data_dir, MOUSE_STROMAL_FILE))
if not isinstance(mouse_stromal_adata.X, csr_matrix):
    mouse_stromal_adata.X = csr_matrix(mouse_stromal_adata.X)

assert isinstance(mouse_stromal_adata.obs, pd.DataFrame)
mouse_stromal_adata.obs["donor"] = mouse_stromal_adata.obs["donor_id"]
mouse_stromal_adata.obs["sample"] = mouse_stromal_adata.obs["biosample_id"]
mouse_stromal_adata.obs["organ"] = mouse_stromal_adata.obs["organ__ontology_label"]
mouse_stromal_adata.obs["genotype"] = mouse_stromal_adata.obs["genotype"]
mouse_stromal_adata.obs["treatment"] = mouse_stromal_adata.obs["treatment"]
mouse_stromal_adata.obs["celltype"] = mouse_stromal_adata.obs["celltype"]
mouse_stromal_adata.obs["x_axis"] = mouse_stromal_adata.obs["x_centroid"]
mouse_stromal_adata.obs["y_axis"] = mouse_stromal_adata.obs["y_centroid"]
mouse_stromal_adata.obs["slide"] = mouse_stromal_adata.obs["slide_id"]
mouse_stromal_adata.obs["broad_celltype"] = "stromal"
mouse_stromal_adata.obs["series"] = SERIES

keep = ["donor", "sample", "organ", "genotype", "treatment", "celltype", "x_axis", "y_axis", "slide", "broad_celltype", "series"]
mouse_stromal_adata.obs.drop(columns = [c for c in mouse_stromal_adata.obs.columns if c not in keep], inplace=True) #type: ignore

mouse_stromal_adata.obs.head() #type: ignore

,organ,genotype,treatment,celltype,donor,sample,x_axis,y_axis,slide,broad_celltype,series
aaagmgej-1-0,colon,WT,DSS,Capillaries,WT1-DSS,WT1-DSS,515.839233,2198.035400,0022827,stromal,pokatayev
aababgkm-1-0,colon,WT,DSS,Arterioles,WT1-DSS,WT1-DSS,370.490112,2569.373779,0022827,stromal,pokatayev
aabdmfdf-1-0,colon,WT,DSS,Glial cells,WT1-DSS,WT1-DSS,403.939453,2534.651123,0022827,stromal,pokatayev
aabfaado-1-0,colon,WT,DSS,Capillaries,WT1-DSS,WT1-DSS,420.581024,2704.686768,0022827,stromal,pokatayev
aabfbfhp-1-0,colon,WT,DSS,Pericytes,WT1-DSS,WT1-DSS,407.785431,2686.849609,0022827,stromal,pokatayev

In [ ]:
mouse_adata_list = [mouse_fibroblast_adata, mouse_epithelial_adata, mouse_immune_adata, mouse_stromal_adata, ]
reference_columns = set(mouse_adata_list[0].obs.columns)

for adata in mouse_adata_list:
    if set(adata.obs.columns) != reference_columns:
        raise ValueError("obs of adatas do not match!")

mouse_adata = ad.concat(mouse_adata_list, join="outer")
del mouse_adata_list
gc.collect()

529

In [ ]:
mouse_adata.obs.index = mouse_adata.obs.index.astype(str)
mouse_adata.var.index = mouse_adata.var.index.astype(str)
mouse_adata.write_h5ad(os.path.join(pre_h5ad_dir, SERIES + "_mouse_raw.h5ad"))
del mouse_adata
gc.collect()

0